version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando dependencias..."
      - pip install -r requirements.txt -t ./package || true
      - echo "DEBUG: LAMBDA_FUNCTION_NAME=$LAMBDA_FUNCTION_NAME"

  pre_build:
    commands:
      - echo "Preparando dist..."
      - mkdir -p dist
      - 'if [ -z "$LAMBDA_FUNCTION_NAME" ]; then echo "ERROR: LAMBDA_FUNCTION_NAME no está definido"; exit 1; fi'
      - 'if [ ! -d "$LAMBDA_FUNCTION_NAME" ]; then echo "ERROR: no existe el directorio \"$LAMBDA_FUNCTION_NAME\""; ls -la; exit 1; fi'
      - 'cd "$LAMBDA_FUNCTION_NAME"'
      - 'zip -r "../dist/${LAMBDA_FUNCTION_NAME}.zip" .'
      - 'cd - > /dev/null'
      - echo "Contenido final del directorio dist:"
      - ls -R dist

  build:
    commands:
      - echo "Empaquetado completado para $LAMBDA_FUNCTION_NAME"

artifacts:
  files:
    - dist/*.zip
