version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando dependencias..."
      - pip install -r requirements.txt -t ./package

  pre_build:
    commands:
      - echo "Estructura..."
      - ls -R
      - echo "Empaquetando funciones Lambda..."
      - mkdir -p dist
      - for dir in */; do
          lambda_name=$(basename $dir);
          echo "Empaquetando $lambda_name...";
          cd $dir;
          zip -r ../dist/$lambda_name.zip .;
          cd - > /dev/null;
        done
      - echo "Contenido final del directorio dist:"
      - ls -R dist

  build:
    commands:
      - echo "Construcción completada."

artifacts:
  files:
    - dist/*.zip
