version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando dependencias..."
      - pip install -r requirements.txt -t ./package

  pre_build:
    commands:
      - echo "Empaquetando función Lambda: $LAMBDA_FUNCTION_NAME"
      - mkdir -p dist
      - |
        if [ ! -d "$LAMBDA_FUNCTION_NAME" ]; then
          echo "Error: No existe el directorio $LAMBDA_FUNCTION_NAME"
          exit 1
        fi
      - cd $LAMBDA_FUNCTION_NAME
      - zip -r ../dist/$LAMBDA_FUNCTION_NAME.zip .
      - cd - > /dev/null
      - echo "Contenido final del directorio dist:"
      - ls -R dist

  build:
    commands:
      - echo "Empaquetado completado para $LAMBDA_FUNCTION_NAME"

artifacts:
  files:
    - dist/*.zip
