version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando dependencias..."
      - pip install -r requirements.txt -t ./package

  pre_build:
    commands:
      - echo "Empaquetando Lambda ROHI_DEV_USER..."
      - mkdir -p tmp
      - cd ROHI_DEV_USER
      - zip -r ../tmp/ROHI_DEV_USER.zip .
      - cd - > /dev/null
      - echo "Descomprimiendo ROHI_DEV_USER.zip..."
      - unzip -o tmp/ROHI_DEV_USER.zip -d .
      - rm -rf tmp
      - echo "Contenido final en raíz del proyecto:"
      - ls -R .

  build:
    commands:
      - echo "Build completado para ROHI_DEV_USER"

artifacts:
  files:
    - '**/*'
  discard-paths: no
