"""add foreing key table

Revision ID: 54c3c3987365
Revises: f826c2ffa494
Create Date: 2025-10-05 20:07:03.792075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c3c3987365'
down_revision: Union[str, Sequence[str], None] = 'f826c2ffa494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_document_id', sa.String(length=15), nullable=False))
    op.create_foreign_key(None, 'patients', 'users', ['user_document_id'], ['document_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_document_id')
    # ### end Alembic commands ###
