"""create patient table

Revision ID: f826c2ffa494
Revises: b9f44dcf199a
Create Date: 2025-10-05 18:46:28.646555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f826c2ffa494'
down_revision: Union[str, Sequence[str], None] = 'b9f44dcf199a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id_pat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent', sa.Boolean(), nullable=False),
    sa.Column('name_agent', sa.String(length=255), nullable=True),
    sa.Column('phone_agent', sa.String(length=13), nullable=True),
    sa.Column('eps', sa.Enum('NE', 'ST', 'C', 'F', name='eps'), nullable=False),
    sa.PrimaryKeyConstraint('id_pat')
    )
    op.create_index(op.f('ix_patients_id_pat'), 'patients', ['id_pat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_id_pat'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
