"""fix varchar lengths in user table

Revision ID: 7ae80155b7c8
Revises: 82f2d7525664
Create Date: 2025-10-05 15:38:45.212010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae80155b7c8'
down_revision: Union[str, Sequence[str], None] = '82f2d7525664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('document_id', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.Enum('CC', 'CE', 'TI', 'PP', 'RC', name='documenttype'), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('sex', sa.Enum('M', 'F', 'NB', 'TS', 'NN', name='sex'), nullable=False),
    sa.Column('rol', sa.Enum('GERENTE', 'ADMIN', 'DOCTOR', 'TERAPEUTA', 'PACIENTE', name='rol'), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_users_document_id'), 'users', ['document_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_document_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
