"""professional model

Revision ID: ce954b89789b
Revises: a8efe647fb78
Create Date: 2025-10-06 07:41:24.425627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce954b89789b'
down_revision: Union[str, Sequence[str], None] = 'a8efe647fb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionals',
    sa.Column('id_prof', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profession', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('vehicle', sa.Boolean(), nullable=False),
    sa.Column('plate_vehicle', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('user_document_id', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_document_id'], ['users.document_id'], ),
    sa.PrimaryKeyConstraint('id_prof'),
    sa.UniqueConstraint('user_document_id')
    )
    op.create_index(op.f('ix_professionals_id_prof'), 'professionals', ['id_prof'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professionals_id_prof'), table_name='professionals')
    op.drop_table('professionals')
    # ### end Alembic commands ###
