"""secretary role

Revision ID: 18823a0c2cc5
Revises: bfee9d311af0
Create Date: 2025-10-27 20:02:05.754292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18823a0c2cc5'
down_revision: Union[str, Sequence[str], None] = 'bfee9d311af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('url_receipt', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'url_receipt')
    # ### end Alembic commands ###
