"""bd v1.2

Revision ID: 2fddb9e91a53
Revises: ce954b89789b
Create Date: 2025-10-26 15:53:39.943216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fddb9e91a53'
down_revision: Union[str, Sequence[str], None] = 'ce954b89789b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('care_type', sa.Boolean(), nullable=False),
    sa.Column('app_type', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('FREE', 'NOT_PAYED', 'PAYED', 'ON_PROGRESS', 'FINISHED', name='appointmentstatus'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id_pat'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id_prof'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histories',
    sa.Column('id_hist', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('background', sa.TEXT(), nullable=False),
    sa.Column('diagnostic', sa.TEXT(), nullable=False),
    sa.Column('manage_plan', sa.TEXT(), nullable=False),
    sa.Column('treatment', sa.TEXT(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id_hist')
    )
    op.create_index(op.f('ix_histories_id_hist'), 'histories', ['id_hist'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_histories_id_hist'), table_name='histories')
    op.drop_table('histories')
    op.drop_table('appointments')
    # ### end Alembic commands ###
