"""secretary role

Revision ID: 91951ca0457b
Revises: 18823a0c2cc5
Create Date: 2025-10-27 20:11:12.631372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91951ca0457b'
down_revision: Union[str, Sequence[str], None] = '18823a0c2cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE users 
        MODIFY rol ENUM('Gerente', 'Administrador', 'Doctor', 'Terapeuta', 'Paciente', 'Secretario') 
        NOT NULL DEFAULT 'Paciente';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE users 
        MODIFY rol ENUM('Gerente', 'Administrador', 'Doctor', 'Terapeuta', 'Paciente') 
        NOT NULL DEFAULT 'Paciente';
    """)
    # ### end Alembic commands ###
