"""secretary role

Revision ID: fff92de6f447
Revises: 91951ca0457b
Create Date: 2025-10-27 20:26:31.821570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fff92de6f447'
down_revision: Union[str, Sequence[str], None] = '91951ca0457b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rol',
               existing_type=mysql.ENUM('Gerente', 'Administrador', 'Doctor', 'Terapeuta', 'Paciente', 'Secretario'),
               type_=sa.Enum('GERENTE', 'ADMIN', 'DOCTOR', 'TERAPEUTA', 'PACIENTE', 'SECRETARIO', name='rol'),
               existing_nullable=False,
               existing_server_default=sa.text("'Paciente'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rol',
               existing_type=sa.Enum('GERENTE', 'ADMIN', 'DOCTOR', 'TERAPEUTA', 'PACIENTE', 'SECRETARIO', name='rol'),
               type_=mysql.ENUM('Gerente', 'Administrador', 'Doctor', 'Terapeuta', 'Paciente', 'Secretario'),
               existing_nullable=False,
               existing_server_default=sa.text("'Paciente'"))
    # ### end Alembic commands ###
